version: 0.1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: build.cmd
artifacts:
- path: pkg\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: IgcvF+a/qRmcsAXvf11jopkDAkdQPG+tY+R+cI0iqnv0/pKUN8Qk5rF3Q43unF9O